name: SorekillTeams
version: ${project.version}
main: net.chumbucket.sorekillteams.SorekillTeamsPlugin
api-version: 1.21
author: Sorekill

softdepend: [PlaceholderAPI, MiniPlaceholders]

commands:
  team:
    description: Manage your team
    usage: /team <create|invite|invites|accept|deny|leave|disband|info|ff|kick|transfer>
    aliases: [teams]
    permission: sorekillteams.use

  tc:
    description: Team chat (toggle or send a message)
    usage: /tc [message...]
    permission: sorekillteams.chat

  sorekillteams:
    description: Admin commands for SorekillTeams
    usage: /sorekillteams <reload|version>
    aliases: [st, stteams]
    permission: sorekillteams.admin

permissions:
  sorekillteams.*:
    description: All SorekillTeams permissions
    default: false
    children:
      sorekillteams.use: true
      sorekillteams.info: true
      sorekillteams.create: true
      sorekillteams.invite: true
      sorekillteams.invites: true
      sorekillteams.accept: true
      sorekillteams.deny: true
      sorekillteams.leave: true
      sorekillteams.disband: true
      sorekillteams.chat: true
      sorekillteams.ff: true
      sorekillteams.kick: true
      sorekillteams.transfer: true
      sorekillteams.admin: true
      sorekillteams.reload: true
      sorekillteams.version: true

  sorekillteams.use:
    description: Use /team
    default: false

  sorekillteams.info:
    description: View your team info
    default: false

  sorekillteams.create:
    description: Create a team
    default: false

  sorekillteams.invite:
    description: Invite players to your team
    default: false

  sorekillteams.invites:
    description: View received invites
    default: false

  sorekillteams.accept:
    description: Accept a team invite
    default: false

  sorekillteams.deny:
    description: Deny a team invite
    default: false

  sorekillteams.leave:
    description: Leave your current team
    default: false

  sorekillteams.disband:
    description: Disband your team (owner only)
    default: false

  sorekillteams.chat:
    description: Use team chat (/tc)
    default: false

  sorekillteams.ff:
    description: Allows using /team ff
    default: false

  sorekillteams.kick:
    description: Kick a member from your team (owner only)
    default: false

  sorekillteams.transfer:
    description: Transfer team ownership to a member (owner only)
    default: false

  sorekillteams.admin:
    description: Use /sorekillteams
    default: false

  sorekillteams.reload:
    description: Reload SorekillTeams config
    default: false

  sorekillteams.version:
    description: View SorekillTeams version info
    default: false
