name: SorekillTeams
version: 1.1.3
main: net.chumbucket.sorekillteams.SorekillTeamsPlugin
api-version: 1.21
author: Sorekill
website: https://github.com/thesorekill/SorekillTeams

softdepend:
  - PlaceholderAPI
  - MiniPlaceholders

commands:
  team:
    description: Teams command
    usage: /team
    aliases: [teams, t]
    permission: sorekillteams.use

  tc:
    description: Send a team chat message (or toggle team chat mode)
    usage: /tc [message...]
    aliases: [teamchat]
    permission: sorekillteams.teamchat

  sorekillteams:
    description: SorekillTeams admin command
    usage: /sorekillteams reload|version|disband|setowner|kick|info
    aliases: [st]
    permission: sorekillteams.admin

permissions:
  # -------------------------
  # Base
  # -------------------------
  sorekillteams.use:
    description: Allows using /team
    default: true

  sorekillteams.admin:
    description: Allows using /sorekillteams (admin controls)
    default: op

  # -------------------------
  # /team reload (player-facing convenience)
  # (TeamCommand checks sorekillteams.reload OR sorekillteams.admin)
  # -------------------------
  sorekillteams.reload:
    description: Allows /team reload
    default: op

  # -------------------------
  # Team management (player)
  # -------------------------
  sorekillteams.create:
    description: Create a team
    default: true

  sorekillteams.invite:
    description: Invite players to your team (owner)
    default: true

  # 1.1.3: invite list has its own permission
  sorekillteams.invites:
    description: View your pending team invites
    default: true

  sorekillteams.accept:
    description: Accept team invites
    default: true

  sorekillteams.deny:
    description: Deny team invites
    default: true

  sorekillteams.leave:
    description: Leave your team
    default: true

  sorekillteams.disband:
    description: Disband your team (owner)
    default: true

  sorekillteams.info:
    description: View team info
    default: true

  sorekillteams.kick:
    description: Kick a member (owner)
    default: true

  sorekillteams.transfer:
    description: Transfer team ownership (owner)
    default: true

  sorekillteams.rename:
    description: Rename your team (owner)
    default: true

  sorekillteams.ff:
    description: Toggle friendly fire for your team (owner)
    default: true

  # -------------------------
  # Team chat
  # -------------------------
  sorekillteams.teamchat:
    description: Use team chat features (toggle/team chat commands)
    default: true

  # Legacy node (backwards compatible with older setups using sorekillteams.chat)
  sorekillteams.chat:
    description: Legacy permission node (use sorekillteams.teamchat instead)
    default: false
    children:
      sorekillteams.teamchat: true

  # -------------------------
  # Team spy
  # -------------------------
  sorekillteams.spy:
    description: Spy on team chat messages
    default: op

  # -------------------------
  # Friendly fire bypass
  # -------------------------
  sorekillteams.friendlyfire.bypass:
    description: Bypass friendly fire protection (damage teammates even if blocked)
    default: op

  # -------------------------
  # Max members permission pattern
  # Example: sorekillteams.max.6 gives max members 6
  # -------------------------
  sorekillteams.max.*:
    description: Permission node pattern for team max sizes
    default: false

  # -------------------------
  # Admin action nodes
  # -------------------------
  sorekillteams.admin.reload:
    description: Reload config/messages/storage
    default: op

  sorekillteams.admin.version:
    description: View plugin version information
    default: op

  sorekillteams.admin.disband:
    description: Force disband a team
    default: op

  sorekillteams.admin.setowner:
    description: Force set owner of a team
    default: op

  sorekillteams.admin.kick:
    description: Force kick a player from a team
    default: op

  sorekillteams.admin.info:
    description: View team info for any team
    default: op

  # -------------------------
  # Team homes
  # -------------------------
  sorekillteams.homes:
    description: View/list team homes
    default: true

  sorekillteams.home:
    description: Teleport to a team home
    default: true

  sorekillteams.sethome:
    description: Set a team home (owner only)
    default: true

  sorekillteams.delhome:
    description: Delete a team home (owner only)
    default: true

  sorekillteams.home.bypasscooldown:
    description: Bypass team home teleport cooldowns
    default: op
