name: Feature request
description: Suggest an improvement or new feature for NetworkNick
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the suggestion! Please describe what you'd like added and why.

  - type: textarea
    id: problem
    attributes:
      label: Problem / use-case
      placeholder: "What problem are you trying to solve?"
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      placeholder: "What would you like NetworkNick to do?"
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      placeholder: "Any alternative approaches you've considered?"
    validations:
      required: false

  - type: textarea
    id: extra
    attributes:
      label: Additional context
      placeholder: "Screenshots, config ideas, related plugins, etc."
    validations:
      required: false
